// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.0
// source: proto/tenant.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "streamgate.tenant";

/** Request payload containing the public routing token */
export interface ValidateKeyRequest {
  apiKey: string;
}

/** Response payload detailing provisioning configurations */
export interface ValidateKeyResponse {
  isValid: boolean;
  tenantId: string;
  rateLimitWindowSec: number;
  maxRequestsPerWindow: number;
  status: string;
}

export const STREAMGATE_TENANT_PACKAGE_NAME = "streamgate.tenant";

/** The Tenant Management Service definition. */

export interface TenantServiceClient {
  validateTenantKey(request: ValidateKeyRequest): Observable<ValidateKeyResponse>;
}

/** The Tenant Management Service definition. */

export interface TenantServiceController {
  validateTenantKey(
    request: ValidateKeyRequest,
  ): Promise<ValidateKeyResponse> | Observable<ValidateKeyResponse> | ValidateKeyResponse;
}

export function TenantServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["validateTenantKey"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TenantService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TenantService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TENANT_SERVICE_NAME = "TenantService";
